{"message": "Exception in ASGI application\n", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py\", line 373, in run_asgi\n    result = await app(self.scope, self.receive, self.send)\n  File \"/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py\", line 75, in __call__\n    return await self.app(scope, receive, send)\n  File \"/usr/local/lib/python3.7/site-packages/uvicorn/middleware/message_logger.py\", line 82, in __call__\n    raise exc from None\n  File \"/usr/local/lib/python3.7/site-packages/uvicorn/middleware/message_logger.py\", line 78, in __call__\n    await self.app(scope, inner_receive, inner_send)\n  File \"/usr/local/lib/python3.7/site-packages/fastapi/applications.py\", line 212, in __call__\n    await super().__call__(scope, receive, send)\n  File \"/usr/local/lib/python3.7/site-packages/starlette/applications.py\", line 112, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 181, in __call__\n    raise exc\n  File \"/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 159, in __call__\n    await self.app(scope, receive, _send)\n  File \"/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py\", line 92, in __call__\n    await self.simple_response(scope, receive, send, request_headers=headers)\n  File \"/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py\", line 147, in simple_response\n    await self.app(scope, receive, send)\n  File \"/usr/local/lib/python3.7/site-packages/starlette/exceptions.py\", line 82, in __call__\n    raise exc\n  File \"/usr/local/lib/python3.7/site-packages/starlette/exceptions.py\", line 71, in __call__\n    await self.app(scope, receive, sender)\n  File \"/usr/local/lib/python3.7/site-packages/starlette/routing.py\", line 656, in __call__\n    await route.handle(scope, receive, send)\n  File \"/usr/local/lib/python3.7/site-packages/starlette/routing.py\", line 259, in handle\n    await self.app(scope, receive, send)\n  File \"/usr/local/lib/python3.7/site-packages/starlette/routing.py\", line 61, in app\n    response = await func(request)\n  File \"/usr/local/lib/python3.7/site-packages/fastapi/routing.py\", line 227, in app\n    dependant=dependant, values=values, is_coroutine=is_coroutine\n  File \"/usr/local/lib/python3.7/site-packages/fastapi/routing.py\", line 159, in run_endpoint_function\n    return await dependant.call(**values)\n  File \"./skill_manager/api.py\", line 223, in query_skill\n    response.raise_for_status()\n  File \"/usr/local/lib/python3.7/site-packages/requests/models.py\", line 960, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://naturalqa_retrieve_span_skill:8002/query", "@timestamp": "2022-02-16T11:40:29.681971", "level": "ERROR", "logger": "uvicorn.error", "application": "SQUARE"}
